# use the latest ubuntu environment (18.04) available on travis
dist: xenial
language: python
os:
- linux

python:
  - "3.6"
  - "3.7"
  - "3.8"


before_install:
  - sudo apt-get install -y libev4 python3-pip python3-setuptools
  - pip3 install pyang pyangbind
  - git clone https://github.com/atolab/zenoh-c && cd zenoh-c && git checkout 0.3.0 && make && sudo make install && cd ..
  - git clone https://github.com/atolab/zenoh-python && cd zenoh-python && git checkout 0.3.0 && python3 setup.py install && cd ..
  - git clone https://github.com/atolab/yaks-python && cd yaks-python && git checkout 0.3.0 && make install && cd ..
  - git clone https://github.com/eclipse-fog05/sdk-python -b master --depth 1 && cd sdk-python && git checkout 0.1.x && make && make install && cd ..

script:
  - make install